[webservers]
web01 ansible_host=127.0.0.1 ansible_port=2221
web02 ansible_host=127.0.0.1 ansible_port=2222

[loadbalancers]
lb01 ansible_host=127.0.0.1 ansible_port=2225

[all:vars]
ansible_user=root
ansible_password=root